name: 'fintech_customer_intelligence'
version: '1.0.0'

profile: 'fintech_customer_intelligence'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fintech_customer_intelligence:
    staging:
      +materialized: view
      +schema: DEV
    marts:
      +materialized: table
      +schema: PROD
